Transactiontoolarge exception fix
gcacace/android-signaturepad pull request #157
Opened 2020-08-13 18:16 UTC by oradkovsky

This is still poorly designed but I think better quality would require much more changes and I don't have time for this. Still, this finally works for my use case.

2022-08-01 06:47 UTC, btremote999 reviewed
I did encounter the same crash issue of TrasactionTooLarge during onSaveInstanceState 
Bundle must not store too huge data (Bitmap) on android 28+ 

ver 1.3.1 unusable . revert back to using ver 1.2.1

2022-08-11 19:02 UTC, gustavocnp95 requested changes
@btremote999 I'm from PrologApp. We've created an fork of this project and re-implemented your changes to see if this resolved the problem and be able to use and maintain the library, because the owner is apparently gone. Testing on android api 21 it worked perfectly. Unfortunately, when I tested on android api 30, it seems to have an weird behavior. When the state is restored, it seems to have a white label on the image, each time on a different place. Do you have any idea of how to solve it?

2022-08-17 12:58 UTC, gustavocnp95 commented
@btremote999 We just created a fork and published with the fix keeping the state saving. For use it you should:

Set jitpack.io url on your project's build.gradle
```
allprojects {
    repositories {
        google()
        maven { url "https://jitpack.io" }
   }
}
```
and then, add into your depedencies this:
    
`implementation 'com.github.prologapp:android-signaturepad:1.0.0'`

2026-07-24 14:54 UTC, gcacace commented
Thanks for this! The `TransactionTooLargeException` (and the related "Could not copy bitmap
to parcel blob" crash) on background/rotation is fixed in **1.4.0**, now on Maven Central:
the pad no longer parcels a raw `Bitmap` — `onSaveInstanceState` stores a PNG-compressed
`byte[]` capped at 256 KB, and over-cap signatures are dropped (pad restores empty) rather
than crashing.

Closing as superseded by the released fix. If you still hit the crash on 1.4.0, please reopen
or open a new issue with a repro. Thanks!

2026-07-24 14:54 UTC, closed without merging